spring:
  datasource:
    url: jdbc:h2:mem:calculadora_financeira
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect