spring:
  datasource:
    url: jdbc:h2:mem:testdb/calculadora_financeira
    username: admin
    password: f1n4nc14l%c4lc
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger