# Spring Boot Configuration

spring:
  application:
    name: calculadora-financeira-core
  profiles:
    active: local

# Server Configuration
server:
  port: 8080

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger

# Banco Central Api Configuration
banco-central-api:
  url: https://www3.bcb.gov.br

# Awesome Api Configuration
economia-awesome-api:
  url: https://economia.awesomeapi.com.br