spring:
  application:
    name: calculadora-financeira-core
  profiles:
    active: "@profileActive@"

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger