spring:
  application:
    name: calculadora-financeira-core
  datasource:
    url: jdbc:postgresql://localhost:5432/calculadora_financeira
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger